# Create a simple NGINX server compose on port 7000 getting image from doker hub

version: '3.1'

services:
  nginx:
    image: nginx
    ports:
    - 7000:80
    volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf


